name: pal
channels:
  - conda-forge
  - pytorch
  - nvidia
  - gurobi
dependencies:
  - python=3.12
  - numpy=1.26.4
  - ipython=8.22.2
  - cvxpy=1.4.2
  - pandas=2.2.1
  - gurobi=11.0.1
  - pytorch=2.2.1
  - torchvision=0.17.1
  - torchaudio=2.2.1
  - pytorch-cuda=12.1
  - tqdm=4.66.2
  - pytorch-lightning=2.2.1
  - lightning-flash=0.6.0
