name: pal
channels:
  - conda-forge
dependencies:
  - ipython=8.22.2
  - lightning-flash=0.6.0
  - numpy=1.26.4
  - pandas=2.2.1
  - python=3.12
  - tqdm=4.66.2
  - omegaconf
  - lightning=2.4.0
  - transformers=4.46.2
  - scikit-learn=1.5.2
  - wandb
  - datasets=2.19.2
  - pip
  - pip:
    - torch==2.2.1
    - torchaudio==2.2.1
    - torchvision==0.17.1
